
import type { Game } from '@/types';
import { Timer, BookOpenText, Globe, Film, Globe2, Music, Puzzle, MapPin, Zap, LayoutGrid } from 'lucide-react';

export const GAMES_DATA: Game[] = [
  {
    id: 'timeguessr',
    name: 'Timeguessr',
    description: 'Guess the year of historical photos within a range.',
    link: 'https://timeguessr.com/',
    icon: Timer,
    averageScore: 18000,
    examplePreviousScores: [15000, 22000, 19000],
  },
  {
    id: 'wordle',
    name: 'Wordle',
    description: 'Guess the hidden 5-letter word in 6 tries.',
    link: 'https://www.nytimes.com/games/wordle/index.html',
    icon: BookOpenText,
    averageScore: 4,
    examplePreviousScores: [3, 4, 5, 4],
  },
  {
    id: 'worldle',
    name: 'Worldle',
    description: 'Guess the country based on its silhouette.',
    link: 'https://worldle.teuteuf.fr/',
    icon: Globe,
    averageScore: 3,
    examplePreviousScores: [2, 3, 4, 1],
  },
  {
    id: 'emovi',
    name: 'Emovi',
    description: 'Guess the movie from a sequence of emojis.',
    link: 'https://emovi.teuteuf.fr/',
    icon: Film,
    averageScore: 3,
    examplePreviousScores: [2, 4, 3],
  },
  {
    id: 'globle',
    name: 'Globle',
    description: 'Guess the mystery country of the world by proximity.',
    link: 'https://globle-game.com/',
    icon: Globe2,
    averageScore: 8,
    examplePreviousScores: [7, 10, 9],
  },
  {
    id: 'bandle',
    name: 'Bandle',
    description: 'Guess the band from a short audio clip.',
    link: 'https://bandle.app/',
    icon: Music,
    averageScore: 3,
    examplePreviousScores: [2, 4, 1],
  },
  {
    id: 'connections',
    name: 'Connections',
    description: 'Group words into categories. Enter mistakes made (0-4).',
    link: 'https://www.nytimes.com/games/connections',
    icon: Puzzle,
    averageScore: 1,
    examplePreviousScores: [0, 1, 2, 0],
  },
  {
    id: 'geoguessr',
    name: 'GeoGuessr Daily',
    description: 'Guess locations based on Street View imagery.',
    link: 'https://www.geoguessr.com/daily-challenges',
    icon: MapPin,
    averageScore: 18000,
    examplePreviousScores: [15000, 20000, 17500],
  },
  {
    id: 'wikispeedrun',
    name: 'Wikipedia Speedrun',
    description: 'Navigate pages. Enter your time in seconds.',
    link: 'https://www.wikispeedruns.com/',
    icon: Zap,
    averageScore: 120,
    examplePreviousScores: [100, 150, 110],
  },
];
