
import type { Game } from '@/types';
import { Timer, BookOpenText, Globe, Film, Globe2, Music, Puzzle, MapPin, Zap, LayoutGrid } from 'lucide-react';

export const GAMES_DATA: Game[] = [
  {
    id: 'timeguessr',
    name: 'Timeguessr',
    description: 'Paste your full "Share" text with the score grid.',
    link: 'https://timeguessr.com/',
    icon: Timer,
    averageScore: 18000,
    examplePreviousScores: [15000, 22000, 19000],
    scoreInputType: 'text',
  },
  {
    id: 'wordle',
    name: 'Wordle',
    description: 'Paste your full "Share" text with the emoji grid.',
    link: 'https://www.nytimes.com/games/wordle/index.html',
    icon: BookOpenText,
    averageScore: 4,
    examplePreviousScores: [3, 4, 5, 4],
    scoreInputType: 'text',
  },
  {
    id: 'worldle',
    name: 'Worldle',
    description: 'Paste your full "Share" text. The app will find your score (e.g., 4/6) automatically.',
    link: 'https://worldle.teuteuf.fr/',
    icon: Globe,
    averageScore: 3,
    examplePreviousScores: [2, 3, 4, 1],
    scoreInputType: 'text',
  },
  {
    id: 'emovi',
    name: 'Emovi',
    description: 'Paste your full "Share" text with the emoji grid.',
    link: 'https://emovi.teuteuf.fr/',
    icon: Film,
    averageScore: 3,
    examplePreviousScores: [2, 4, 3],
    scoreInputType: 'text',
  },
  {
    id: 'globle',
    name: 'Globle',
    description: "Paste your full 'Share' text. The app will find your number of guesses.",
    link: 'https://globle-game.com/',
    icon: Globe2,
    averageScore: 8,
    examplePreviousScores: [7, 10, 9],
    scoreInputType: 'text',
  },
  {
    id: 'bandle',
    name: 'Bandle',
    description: 'Paste your full "Share" text with the emoji grid.',
    link: 'https://bandle.app/',
    icon: Music,
    averageScore: 3,
    examplePreviousScores: [2, 4, 1],
    scoreInputType: 'text',
  },
  {
    id: 'connections',
    name: 'Connections',
    description: 'Enter the number of mistakes you made (0-4).',
    link: 'https://www.nytimes.com/games/connections',
    icon: Puzzle,
    averageScore: 1,
    examplePreviousScores: [0, 1, 2, 0],
    scoreInputType: 'number',
  },
  {
    id: 'geoguessr',
    name: 'GeoGuessr Daily',
    description: 'Enter your final score (e.g., 18000).',
    link: 'https://www.geoguessr.com/daily-challenges',
    icon: MapPin,
    averageScore: 18000,
    examplePreviousScores: [15000, 20000, 17500],
    scoreInputType: 'number',
  },
  {
    id: 'wikispeedrun',
    name: 'Wikipedia Speedrun',
    description: 'Enter your time in seconds.',
    link: 'https://www.wikispeedruns.com/',
    icon: Zap,
    averageScore: 120,
    examplePreviousScores: [100, 150, 110],
    scoreInputType: 'number',
  },
];
