
import type { LibraryGame } from '@/types';

export const LIBRARY_GAMES_DATA: LibraryGame[] = [
    { name: 'Angle', link: 'https://angle.wtf/' },
    { name: 'Anti-Wordle', link: 'https://www.antiwordle.com/' },
    { name: 'Bandle', link: 'https://bandle.app/' },
    { name: 'Boardle', link: 'https://playboardle.com/' },
    { name: 'Connections', link: 'https://www.nytimes.com/games/connections' },
    { name: 'Contexto', link: 'https://contexto.me/en/' },
    { name: 'Costcodle', link: 'https://costcodle.com/' },
    { name: 'Graphs', link: 'https://www.graphs.world/' },
    { name: 'Daydle', link: 'https://daydle.com/' },
    { name: 'Emovi', link: 'https://emovi.teuteuf.fr/' },
    { name: 'Etymoleon', link: 'https://etymoleon.com/game' },
    { name: 'Flagle', link: 'https://www.flagle.io/' },
    { name: 'FoodGuessr', link: 'https://www.foodguessr.com/' },
    { name: 'Framed', link: 'https://framed.wtf/' },
    { name: 'Gamedle', link: 'https://www.gamedle.wtf/' },
    { name: 'Geodle', link: 'https://geodle.me/' },
    { name: 'GeoGrid', link: 'https://www.geogridgame.com/' },
    { name: 'GeoGuessr', link: 'https://www.geoguessr.com/' },
    { name: 'Globle', link: 'https://globle-game.com/' },
    { name: 'Google Fued', link: 'https://googlefeud.com/' },
    { name: 'Guess the Game', link: 'https://guessthe.game/' },
    { name: 'Heardle', link: 'https://heardlewordle.io/' },
    { name: 'Hexcodle', link: 'https://hexcodle.com/' },
    { name: 'Housle', link: 'https://housle.house/' },
    { name: 'Letterle', link: 'https://edjefferson.com/letterle/' },
    { name: 'Listed', link: 'https://listed.fun/' },
    { name: 'Mini Crossword', link: 'https://www.nytimes.com/crosswords/game/mini' },
    { name: 'More/Less', link: 'https://lessgames.com/moreless' },
    { name: 'Movie to Movie', link: 'https://movietomovie.com/' },
    { name: 'MovieGrid', link: 'https://moviegrid.io/' },
    { name: 'Nerdle', link: 'https://nerdlegame.com/' },
    { name: 'Phrazle', link: 'https://phrazle.gg/' },
    { name: 'PokeDoku', link: 'https://pokedoku.com/' },
    { name: 'Searchle', link: 'https://searchle.net/' },
    { name: 'Songless', link: 'https://lessgames.com/songless' },
    { name: 'Spotle', link: 'https://spotle.io/' },
    { name: 'Squirdle', link: 'https://squirdle.fireblend.com/' },
    { name: 'Statle', link: 'https://statele.teuteuf.fr/' },
    { name: 'Steamdle', link: 'https://steamdle.com/' },
    { name: 'Sudoku', link: 'https://www.nytimes.com/puzzles/sudoku' },
    { name: 'Timeguessr', link: 'https://timeguessr.com/' },
    { name: 'Tradle', link: 'https://oec.world/en/games/tradle' },
    { name: 'Travle', link: 'https://travle.earth/' },
    { name: 'Wiki Speedrun', link: 'https://wikispeedruns.com/' },
    { name: 'WikiTrivia', link: 'https://wikitrivia.tomjwatson.com/' },
    { name: 'Word Salad', link: 'https://wordsalad.online/' },
    { name: 'Word Waffle', link: 'https://wafflegame.net/daily' },
    { name: 'Word Weaver', link: 'https://wordwormdormdork.com/' },
    { name: 'Wordle', link: 'https://www.nytimes.com/games/wordle/index.html' },
    { name: 'Worldle', link: 'https://worldle.teuteuf.fr/' },
    { name: 'Circuits', link: 'https://circuitsgame.com/' },
    { name: 'The Letter Loop', link: 'https://www.theletterloop.com/' },
    { name: 'Orbits', link: 'https://www.playorbits.com/' },
    { name: 'Top Five', link: 'https://topfivetrivia.com/' },
    { name: 'PinPoint', link: 'https://www.linkedin.com/games/pinpoint' },
    { name: 'Timewaster', link: 'https://www.thesmokinggun.com/time-waster' },
    { name: 'Hexle', link: 'https://frankljin.github.io/hexle/' },
    { name: 'Victordle', link: 'https://www.britannica.com/games/victordle/' },
    { name: 'Cyphr', link: 'https://cyphrgame.com/' },
    { name: 'Toppled', link: 'https://bythomas.co.uk/toppled/' },
    { name: 'Squardle', link: 'https://fubargames.se/squardle/' },
    { name: 'Puzzmo', link: 'https://www.puzzmo.com/today' },
    { name: 'Francele', link: 'https://francele.teuteuf.fr/' },
    { name: 'GeoConnections', link: 'https://geoconnections.net/' },
    { name: 'KeyWord', link: 'https://www.washingtonpost.com/games/keyword/' },
    { name: 'Minecraftle', link: 'https://minecraftle.zachmanson.com/' },
    { name: 'Metazooa', link: 'https://metazooa.com/' },
    { name: 'Chessle', link: 'https://jackli.gg/chessle/' },
    { name: 'Posterdle', link: 'https://posterdle.io/unlimited' },
    { name: 'unWordle', link: 'https://unwordle.io/?daily=1' },
    { name: 'Flagl', link: 'https://www.flagl.net/' },
    { name: 'Hurdle', link: 'https://playhurdle.vercel.app/' },
    { name: 'Factle', link: 'https://frontofficesports.com/trivia/factle/' },
    { name: 'Squaredle', link: 'https://squaredle.app/' },
    { name: 'Strands', link: 'https://www.nytimes.com/games/strands?smtyp=cur&smid=bsky-nytimes' },
    { name: 'LetterBoxed', link: 'https://www.nytimes.com/puzzles/letter-boxed' },
    { name: 'CryptoGram', link: 'https://api.razzlepuzzles.com/cryptogram' },
    { name: 'CrossClimb', link: 'https://www.linkedin.com/games/crossclimb' },
    { name: 'Queens', link: 'https://www.linkedin.com/games/queens' },
    { name: 'Quizl', link: 'https://quizl.io/' },
    { name: 'Learnle', link: 'https://learnle.net/' },
    { name: 'Primel', link: 'https://converged.yt/primel/' },
    { name: 'Absurdle', link: 'https://qntm.org/files/absurdle/absurdle.html' },
    { name: 'SquareWord', link: 'https://squareword.org/' },
    { name: 'CrossWordle', link: 'https://crosswordle.serializer.ca/' },
    { name: 'ReVertle', link: 'https://www.puppetsquid.com/revertle' },
    { name: 'Brickdle', link: 'https://www.brickdle.com/' },
    { name: 'Cardle', link: 'https://cardle.uk/' },
    { name: 'Eruptle', link: 'https://eruptle.app/' },
    { name: 'Sorted', link: 'https://puzzles-prod.telegraph.co.uk/sorted/index.html' },
    { name: 'DailyTens', link: 'https://dailytens.com/' },
    { name: 'GuessTen', link: 'https://guessten.com' },
    { name: 'Artle', link: 'https://www.nga.gov/artle' },
    { name: 'Dungleon', link: 'https://www.dungleon.com/' },
    { name: 'Facedle', link: 'https://facedle.app' },
    { name: 'KindaHardGolf', link: 'https://kindahardgolf.com/' },
    { name: 'Picsey', link: 'https://picsey.io/' },
    { name: 'Talldle', link: 'https://www.talldle.com/' },
    { name: 'Rogule', link: 'https://rogule.com/game.html' },
    { name: 'ThreeMagicWords', link: 'https://www.threemagicwords.app/play' },
    { name: 'Birdle', link: 'https://www.play-birdle.com/' },
    { name: 'Triplets', link: 'https://www.tripletgame.com/' },
    { name: 'Shaple', link: 'https://swag.github.io/shaple/' },
    { name: 'Zip', link: 'https://www.linkedin.com/games/zip' },
    { name: 'FlagDoku', link: 'https://flagdoku.com/' },
];
