
import type { LibraryGame } from '@/types';

export const LIBRARY_GAMES_DATA: LibraryGame[] = [
    { id: 'angle', name: 'Angle', link: 'https://angle.wtf/', rating: 5 },
    { id: 'anti-wordle', name: 'Anti-Wordle', link: 'https://www.antiwordle.com/', rating: 5 },
    { id: 'bandle', name: 'Bandle', link: 'https://bandle.app/', rating: 5 },
    { id: 'boardle', name: 'Boardle', link: 'https://playboardle.com/', rating: 5 },
    { id: 'connections', name: 'Connections', link: 'https://www.nytimes.com/games/connections', rating: 8 },
    { id: 'contexto', name: 'Contexto', link: 'https://contexto.me/en/', rating: 6 },
    { id: 'costcodle', name: 'Costcodle', link: 'https://costcodle.com/', rating: 5 },
    { id: 'graphs', name: 'Graphs', link: 'https://www.graphs.world/', rating: 5 },
    { id: 'daydle', name: 'Daydle', link: 'https://daydle.com/', rating: 5 },
    { id: 'emovi', name: 'Emovi', link: 'https://emovi.teuteuf.fr/', rating: 7 },
    { id: 'etymoleon', name: 'Etymoleon', link: 'https://etymoleon.com/game', rating: 5 },
    { id: 'flagle', name: 'Flagle', link: 'https://www.flagle.io/', rating: 6 },
    { id: 'foodguessr', name: 'FoodGuessr', link: 'https://www.foodguessr.com/', rating: 5 },
    { id: 'framed', name: 'Framed', link: 'https://framed.wtf/', rating: 7 },
    { id: 'gamedle', name: 'Gamedle', link: 'https://www.gamedle.wtf/', rating: 5 },
    { id: 'geodle', name: 'Geodle', link: 'https://geodle.me/', rating: 5 },
    { id: 'geogrid', name: 'GeoGrid', link: 'https://www.geogridgame.com/', rating: 5 },
    { id: 'geoguessr', name: 'GeoGuessr', link: 'https://www.geoguessr.com/', rating: 9 },
    { id: 'globle', name: 'Globle', link: 'https://globle-game.com/', rating: 7 },
    { id: 'google-fued', name: 'Google Fued', link: 'https://googlefeud.com/', rating: 6 },
    { id: 'guess-the-game', name: 'Guess the Game', link: 'https://guessthe.game/', rating: 5 },
    { id: 'heardle', name: 'Heardle', link: 'https://heardlewordle.io/', rating: 7 },
    { id: 'hexcodle', name: 'Hexcodle', link: 'https://hexcodle.com/', rating: 5 },
    { id: 'housle', name: 'Housle', link: 'https://housle.house/', rating: 5 },
    { id: 'letterle', name: 'Letterle', link: 'https://edjefferson.com/letterle/', rating: 3 },
    { id: 'listed', name: 'Listed', link: 'https://listed.fun/', rating: 5 },
    { id: 'mini-crossword', name: 'Mini Crossword', link: 'https://www.nytimes.com/crosswords/game/mini', rating: 8 },
    { id: 'more-or-less', name: 'More/Less', link: 'https://lessgames.com/moreless', rating: 4 },
    { id: 'movie-to-movie', name: 'Movie to Movie', link: 'https://movietomovie.com/', rating: 5 },
    { id: 'moviegrid', name: 'MovieGrid', link: 'https://moviegrid.io/', rating: 6 },
    { id: 'nerdle', name: 'Nerdle', link: 'https://nerdlegame.com/', rating: 6 },
    { id: 'phrazle', name: 'Phrazle', link: 'https://phrazle.gg/', rating: 5 },
    { id: 'pokedoku', name: 'PokeDoku', link: 'https://pokedoku.com/', rating: 6 },
    { id: 'searchle', name: 'Searchle', link: 'https://searchle.net/', rating: 5 },
    { id: 'songless', name: 'Songless', link: 'https://lessgames.com/songless', rating: 5 },
    { id: 'spotle', name: 'Spotle', link: 'https://spotle.io/', rating: 5 },
    { id: 'squirdle', name: 'Squirdle', link: 'https://squirdle.fireblend.com/', rating: 5 },
    { id: 'statle', name: 'Statle', link: 'https://statele.teuteuf.fr/', rating: 6 },
    { id: 'steamdle', name: 'Steamdle', link: 'https://steamdle.com/', rating: 5 },
    { id: 'sudoku', name: 'Sudoku', link: 'https://www.nytimes.com/puzzles/sudoku', rating: 7 },
    { id: 'timeguessr', name: 'Timeguessr', link: 'https://timeguessr.com/', rating: 8 },
    { id: 'tradle', name: 'Tradle', link: 'https://oec.world/en/games/tradle', rating: 6 },
    { id: 'travle', name: 'Travle', link: 'https://travle.earth/', rating: 5 },
    { id: 'wiki-speedrun', name: 'Wiki Speedrun', link: 'https://wikispeedruns.com/', rating: 6 },
    { id: 'wikitrivia', name: 'WikiTrivia', link: 'https://wikitrivia.tomjwatson.com/', rating: 7 },
    { id: 'word-salad', name: 'Word Salad', link: 'https://wordsalad.online/', rating: 5 },
    { id: 'word-waffle', name: 'Word Waffle', link: 'https://wafflegame.net/daily', rating: 5 },
    { id: 'word-weaver', name: 'Word Weaver', link: 'https://wordwormdormdork.com/', rating: 5 },
    { id: 'wordle', name: 'Wordle', link: 'https://www.nytimes.com/games/wordle/index.html', rating: 9 },
    { id: 'worldle', name: 'Worldle', link: 'https://worldle.teuteuf.fr/', rating: 8 },
    { id: 'circuits', name: 'Circuits', link: 'https://circuitsgame.com/', rating: 5 },
    { id: 'the-letter-loop', name: 'The Letter Loop', link: 'https://www.theletterloop.com/', rating: 5 },
    { id: 'orbits', name: 'Orbits', link: 'https://www.playorbits.com/', rating: 5 },
    { id: 'top-five', name: 'Top Five', link: 'https://topfivetrivia.com/', rating: 5 },
    { id: 'pinpoint', name: 'PinPoint', link: 'https://www.linkedin.com/games/pinpoint', rating: 6 },
    { id: 'timewaster', name: 'Timewaster', link: 'https://www.thesmokinggun.com/time-waster', rating: 2 },
    { id: 'hexle', name: 'Hexle', link: 'https://frankljin.github.io/hexle/', rating: 5 },
    { id: 'victordle', name: 'Victordle', link: 'https://www.britannica.com/games/victordle/', rating: 5 },
    { id: 'cyphr', name: 'Cyphr', link: 'https://cyphrgame.com/', rating: 5 },
    { id: 'toppled', name: 'Toppled', link: 'https://bythomas.co.uk/toppled/', rating: 5 },
    { id: 'squardle', name: 'Squardle', link: 'https://fubargames.se/squardle/', rating: 5 },
    { id: 'puzzmo', name: 'Puzzmo', link: 'https://www.puzzmo.com/today', rating: 6 },
    { id: 'francele', name: 'Francele', link: 'https://francele.teuteuf.fr/', rating: 5 },
    { id: 'geoconnections', name: 'GeoConnections', link: 'https://geoconnections.net/', rating: 5 },
    { id: 'keyword', name: 'KeyWord', link: 'https://www.washingtonpost.com/games/keyword/', rating: 6 },
    { id: 'minecraftle', name: 'Minecraftle', link: 'https://minecraftle.zachmanson.com/', rating: 4 },
    { id: 'metazooa', name: 'Metazooa', link: 'https://metazooa.com/', rating: 5 },
    { id: 'chessle', name: 'Chessle', link: 'https://jackli.gg/chessle/', rating: 6 },
    { id: 'posterdle', name: 'Posterdle', link: 'https://posterdle.io/unlimited', rating: 5 },
    { id: 'unwordle', name: 'unWordle', link: 'https://unwordle.io/?daily=1', rating: 5 },
    { id: 'flagl', name: 'Flagl', link: 'https://www.flagl.net/', rating: 5 },
    { id: 'hurdle', name: 'Hurdle', link: 'https://playhurdle.vercel.app/', rating: 5 },
    { id: 'factle', name: 'Factle', link: 'https://frontofficesports.com/trivia/factle/', rating: 5 },
    { id: 'squaredle', name: 'Squaredle', link: 'https://squaredle.app/', rating: 6 },
    { id: 'strands', name: 'Strands', link: 'https://www.nytimes.com/games/strands', rating: 7 },
    { id: 'letterboxed', name: 'LetterBoxed', link: 'https://www.nytimes.com/puzzles/letter-boxed', rating: 6 },
    { id: 'cryptogram', name: 'CryptoGram', link: 'https://api.razzlepuzzles.com/cryptogram', rating: 5 },
    { id: 'crossclimb', name: 'CrossClimb', link: 'https://www.linkedin.com/games/crossclimb', rating: 5 },
    { id: 'queens', name: 'Queens', link: 'https://www.linkedin.com/games/queens', rating: 5 },
    { id: 'quizl', name: 'Quizl', link: 'https://quizl.io/', rating: 5 },
    { id: 'learnle', name: 'Learnle', link: 'https://learnle.net/', rating: 5 },
    { id: 'primel', name: 'Primel', link: 'https://converged.yt/primel/', rating: 5 },
    { id: 'absurdle', name: 'Absurdle', link: 'https://qntm.org/files/absurdle/absurdle.html', rating: 5 },
    { id: 'squareword', name: 'SquareWord', link: 'https://squareword.org/', rating: 5 },
    { id: 'crosswordle', name: 'CrossWordle', link: 'https://crosswordle.serializer.ca/', rating: 5 },
    { id: 'revertle', name: 'ReVertle', link: 'https://www.puppetsquid.com/revertle', rating: 5 },
    { id: 'brickdle', name: 'Brickdle', link: 'https://www.brickdle.com/', rating: 5 },
    { id: 'cardle', name: 'Cardle', link: 'https://cardle.uk/', rating: 5 },
    { id: 'eruptle', name: 'Eruptle', link: 'https://eruptle.app/', rating: 5 },
    { id: 'sorted', name: 'Sorted', link: 'https://puzzles-prod.telegraph.co.uk/sorted/index.html', rating: 5 },
    { id: 'dailytens', name: 'DailyTens', link: 'https://dailytens.com/', rating: 5 },
    { id: 'guessten', name: 'GuessTen', link: 'https://guessten.com', rating: 5 },
    { id: 'artle', name: 'Artle', link: 'https://www.nga.gov/artle', rating: 6 },
    { id: 'dungleon', name: 'Dungleon', link: 'https://www.dungleon.com/', rating: 5 },
    { id: 'facedle', name: 'Facedle', link: 'https://facedle.app', rating: 5 },
    { id: 'kindahardgolf', name: 'KindaHardGolf', link: 'https://kindahardgolf.com/', rating: 5 },
    { id: 'picsey', name: 'Picsey', link: 'https://picsey.io/', rating: 5 },
    { id: 'talldle', name: 'Talldle', link: 'https://www.talldle.com/', rating: 5 },
    { id: 'rogule', name: 'Rogule', link: 'https://rogule.com/game.html', rating: 5 },
    { id: 'threemagicwords', name: 'ThreeMagicWords', link: 'https://www.threemagicwords.app/play', rating: 5 },
    { id: 'birdle', name: 'Birdle', link: 'https://www.play-birdle.com/', rating: 5 },
    { id: 'triplets', name: 'Triplets', link: 'https://www.tripletgame.com/', rating: 5 },
    { id: 'shaple', name: 'Shaple', link: 'https://swag.github.io/shaple/', rating: 5 },
    { id: 'zip', name: 'Zip', link: 'https://www.linkedin.com/games/zip', rating: 5 },
    { id: 'flagdoku', name: 'FlagDoku', link: 'https://flagdoku.com/', rating: 5 },
];
